#!/bin/sh -x

# Wrapper around miner-reallyreset that checks for 
# reset-disabling flag file in /tmp


M=`miner-name $1`
if ! [ -f /tmp/$M.no-reset ]; then 
	miner-reallyreset $M
else 
	echo Not rebooting because of /tmp/$M.no-reset
fi 

